# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-30 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='Dob',
            field=models.DateField(),
        ),
    ]
