# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-30 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20180530_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='Dob',
        ),
    ]
