# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-31 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_Name', models.CharField(default='name', max_length=250)),
                ('school_Img', models.CharField(max_length=250)),
                ('school_distance', models.IntegerField()),
                ('school_address', models.CharField(max_length=1000)),
                ('school_desc', models.CharField(max_length=1500)),
                ('school_Location', models.CharField(max_length=1000)),
                ('school_contact', models.IntegerField()),
                ('school_Email', models.CharField(max_length=250)),
                ('school_WebAddress', models.CharField(max_length=250)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.Area')),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='FirstName',
            field=models.CharField(default='name', max_length=250),
        ),
    ]
