# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-01 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_auto_20180601_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='school_contact',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='schools',
            name='school_distance',
            field=models.IntegerField(),
        ),
    ]
